#!/usr/bin/env python3
import sys
import socket
import time

import pandas as pd


def main(*args):
    if len(args) < 3:
        print(f"usage: python3 {args[0]} <hostname> <port>")
        sys.exit(1)

    UDP_IP = args[1]
    UDP_PORT = int(args[2])
    SERVER_SOCK = (UDP_IP, UDP_PORT)

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    sock.sendto(b'all', SERVER_SOCK)
    resp = sock.recv(4096).decode()
    data = pd.read_json(resp)
    print(data[['Item ID', 'Item Description']].to_string(index=False))

    while True:
        message = input('Enter an item id to query: ')
        if message == 'Bye.':
            break

        RTT_start = time.time()
        sock.sendto(message.encode("UTF-8"), SERVER_SOCK)
        resp = sock.recv(4096).decode()
        RTT_end = time.time()

        rtt = (RTT_end - RTT_start)*1000
        data = pd.read_json(resp)
        print(data.to_string(index=False))
        print(f"RTT of Query: {rtt:5.0f}ms")

        ans = ""
        while ans not in ["y", "n"]:
            ans = input('Do another query? (y/n): ').lower()

        if ans == 'n':
            break

    sock.close()


if __name__ == "__main__":
    main(*sys.argv)
